### ISSUE TITLE
Cluster IPs do not work on Calico when default GW interface is different from Calico interface

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1338]
Originally reported as https://github.com/kubernetes-incubator/kargo/issues/524, they worked around by adding the `--masquerade-all` flag to kube-proxy, which breaks Calico policy

Quoting from that issue:

Bare-metal lab (i.e. cloud_provider is undefined), calico pool without ipip tunneling.

If we have default route via one interface (let's say eth1) and calico routes PoD IPs via another interface (eth0) then cluster IPs provided by kube-proxy do not work.

Routes on node:
```
default via 172.16.0.1 dev eth1
10.233.67.128/26 via 10.90.31.3 dev eth0  proto bird 
```
When we try to connect to any service our packets are NATed to the proper pod. Here's an example, we're trying to connect from the node with routes provided above to dashboard service:
```
#svc
kubernetes-dashboard   10.233.0.126   <nodes>       80/TCP
#pod
kubernetes-dashboard-1329293578-l3e9m   1/1       Running   0          3h        10.233.67.129   node4
```
So our packets to 10.233.0.126:80 (cluster IP) are routed via default gateway (dev eth1), so they have:
```
SRC IP: 172.16.0.38
DST IP: 10.233.0.126
FROM: eth1
```
Then iptables changes DST IP and port to 10.233.67.129:9090:
```
   0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kubernetes-dashboard: */ tcp to:10.233.67.129:9090
```
So packets go out through eth1 interface to the new destination but they still have SRC IP of interface eth0:
```
SRC IP: 172.16.0.38
DST IP: 10.233.67.129
FROM: eth0
```
```
12:50:12.026152 64:1a:69:a7:b1:d3 > 64:01:36:34:45:17, ethertype IPv4 (0x0800), length 74: 172.16.0.38.56172 > 10.233.67.129.9090: Flags [S], seq 2172961666, win 29200, options [mss 1460,sackOK,TS val 3108142 ecr 0,nop,wscale 7], length 0
```

In order to fix this outgoing packets should have a proper SRC IP, then everything works fine:
```
13:00:29.601758 64:1a:69:a7:b1:d3 > 64:01:36:34:45:17, ethertype IPv4 (0x0800), length 74: 10.90.31.6.56482 > 10.233.67.129.9090: Flags [S], seq 1090475453, win 29200, options [mss 1460,sackOK,TS val 3262536 ecr 0,nop,wscale 7], length 0
```

**Comment by caseydavenport** [comment]
@fasaxc this isn't a Calico specific issue, and is generally fixed by passing the `--cluster-cidr=<...>` flag to the kube-proxy, which will ensure the packets are MASQUERADED after going through the proxy's Service DNAT.

Felix could probably install similar chains itself based on IP Pools, but there is an option to do this in the kube-proxy.  I'll make sure that's clear in the original issue.

**Comment by fasaxc** [comment]
@caseydavenport Still not sure I quite follow, doesn't any SNAT generally interfere with our policy?

**Comment by caseydavenport** [comment]
@fasaxc IIUC, this issue only affects traffic from Pods with `hostNetwork: true`, so regular pod->pod traffic won't be affected and policy will still work.

There is still a question of how it affects policy on host networked pods.

**Comment by fasaxc** [comment]
I don't think we apply any policy to host networked pods.  They don't have a cali interface at all.

Closing since it sounds like this is a know issue with known workaround.

**Comment by caseydavenport** [comment]
> I don't think we apply any policy to host networked pods.

Correct.  I was thinking more along the lines "if/when we apply policy to host networked pods", but I think this can be closed for now and we'll cross that bridge later.
